<?php
/**
 * Created by PhpStorm.
 * User: rhutterer
 * Date: 24.07.14
 * Time: 10:34
 */

$installer = $this;

$installer->run("
TRUNCATE checkoutrule;
INSERT INTO `checkoutrule` (`name`,`description`,`from_date`,`to_date`,`customer_group_ids`,`is_active`,`conditions_serialized`,`actions_serialized`,`stop_rules_processing`,`is_advanced`,`product_ids`,`sort_order`,`simple_action`,`payment_methods_ids`,`shipping_methods_ids`,`website_ids`,`coupon_type`) VALUES ('Bezahltmethoden für Abholung im Werksverkauf','','2014-07-23',NULL,'0,1,2,3,4,5,6,9',1,'a:7:{s:4:\"type\";s:32:\"salesrule/rule_condition_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";s:1:\"1\";s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";s:10:\"conditions\";a:2:{i:0;a:5:{s:4:\"type\";s:32:\"salesrule/rule_condition_address\";s:9:\"attribute\";s:9:\"remote_ip\";s:8:\"operator\";s:2:\"==\";s:5:\"value\";s:11:\"100.0.16.72\";s:18:\"is_value_processed\";b:0;}i:1;a:5:{s:4:\"type\";s:32:\"salesrule/rule_condition_address\";s:9:\"attribute\";s:15:\"shipping_method\";s:8:\"operator\";s:2:\"==\";s:5:\"value\";s:25:\"freeshipping_freeshipping\";s:18:\"is_value_processed\";b:0;}}}','a:6:{s:4:\"type\";s:40:\"salesrule/rule_condition_product_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";b:1;s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";}',1,1,NULL,0,'disable_payment_method','checkmo,free,paypal_billing_agreement,computopcw_creditcard,computopcw_directdebits,phoenix_cashondelivery','','2,4,3',1);
INSERT INTO `checkoutrule` (`name`,`description`,`from_date`,`to_date`,`customer_group_ids`,`is_active`,`conditions_serialized`,`actions_serialized`,`stop_rules_processing`,`is_advanced`,`product_ids`,`sort_order`,`simple_action`,`payment_methods_ids`,`shipping_methods_ids`,`website_ids`,`coupon_type`) VALUES ('Barzahlung allgemein deaktivieren (wenn nicht im Werksverkauf)','','2014-07-23',NULL,'0,1,2,3,4,5,6,9',1,'a:7:{s:4:\"type\";s:32:\"salesrule/rule_condition_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";s:1:\"1\";s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";s:10:\"conditions\";a:1:{i:0;a:5:{s:4:\"type\";s:32:\"salesrule/rule_condition_address\";s:9:\"attribute\";s:9:\"remote_ip\";s:8:\"operator\";s:2:\"!=\";s:5:\"value\";s:11:\"100.0.16.72\";s:18:\"is_value_processed\";b:0;}}}','a:6:{s:4:\"type\";s:40:\"salesrule/rule_condition_product_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";b:1;s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";}',1,1,NULL,0,'disable_payment_method','cashondelivery','','2,4,3',1);
INSERT INTO `checkoutrule` (`name`,`description`,`from_date`,`to_date`,`customer_group_ids`,`is_active`,`conditions_serialized`,`actions_serialized`,`stop_rules_processing`,`is_advanced`,`product_ids`,`sort_order`,`simple_action`,`payment_methods_ids`,`shipping_methods_ids`,`website_ids`,`coupon_type`) VALUES ('Bezahlmethoden Gast,Kunde, Geschäftskunde','','2014-07-24',NULL,'0,1,2',1,'a:6:{s:4:\"type\";s:32:\"salesrule/rule_condition_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";s:1:\"1\";s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";}','a:6:{s:4:\"type\";s:40:\"salesrule/rule_condition_product_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";b:1;s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";}',1,1,NULL,0,'disable_payment_method','checkmo,free,paypal_billing_agreement','','2,4,3',1);
INSERT INTO `checkoutrule` (`name`,`description`,`from_date`,`to_date`,`customer_group_ids`,`is_active`,`conditions_serialized`,`actions_serialized`,`stop_rules_processing`,`is_advanced`,`product_ids`,`sort_order`,`simple_action`,`payment_methods_ids`,`shipping_methods_ids`,`website_ids`,`coupon_type`) VALUES ('Bezahltmethoden für Töchter, Märkte und Servicepartner','','2014-07-24',NULL,'3,4,5,6',1,'a:6:{s:4:\"type\";s:32:\"salesrule/rule_condition_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";s:1:\"1\";s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";}','a:6:{s:4:\"type\";s:40:\"salesrule/rule_condition_product_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";b:1;s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";}',1,1,NULL,0,'disable_payment_method','free,paypal_billing_agreement,computopcw_creditcard,computopcw_directdebits','','2,3',1);
INSERT INTO `checkoutrule` (`name`,`description`,`from_date`,`to_date`,`customer_group_ids`,`is_active`,`conditions_serialized`,`actions_serialized`,`stop_rules_processing`,`is_advanced`,`product_ids`,`sort_order`,`simple_action`,`payment_methods_ids`,`shipping_methods_ids`,`website_ids`,`coupon_type`) VALUES ('Abholung allgemein deaktivieren (wenn nicht im Werksverkauf)','','2014-07-25',NULL,'0,1,2,3,4,5,6,9',1,'a:7:{s:4:\"type\";s:32:\"salesrule/rule_condition_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";s:1:\"1\";s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";s:10:\"conditions\";a:1:{i:0;a:5:{s:4:\"type\";s:32:\"salesrule/rule_condition_address\";s:9:\"attribute\";s:9:\"remote_ip\";s:8:\"operator\";s:2:\"!=\";s:5:\"value\";s:11:\"100.0.16.72\";s:18:\"is_value_processed\";b:0;}}}','a:6:{s:4:\"type\";s:40:\"salesrule/rule_condition_product_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";b:1;s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";}',1,1,NULL,10,'disable_shipping_method','','flatrate,freeshipping,tablerate,dhl,fedex,ups,usps,dhlint','2,4,3',1);
INSERT INTO `checkoutrule` (`name`,`description`,`from_date`,`to_date`,`customer_group_ids`,`is_active`,`conditions_serialized`,`actions_serialized`,`stop_rules_processing`,`is_advanced`,`product_ids`,`sort_order`,`simple_action`,`payment_methods_ids`,`shipping_methods_ids`,`website_ids`,`coupon_type`) VALUES ('Liefermethoden für Werksverkauf','','2014-07-25',NULL,'0,1,2,3,4,5,6,9',1,'a:7:{s:4:\"type\";s:32:\"salesrule/rule_condition_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";s:1:\"1\";s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"any\";s:10:\"conditions\";a:1:{i:0;a:5:{s:4:\"type\";s:32:\"salesrule/rule_condition_address\";s:9:\"attribute\";s:9:\"remote_ip\";s:8:\"operator\";s:2:\"==\";s:5:\"value\";s:11:\"100.0.16.72\";s:18:\"is_value_processed\";b:0;}}}','a:6:{s:4:\"type\";s:40:\"salesrule/rule_condition_product_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";b:1;s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";}',1,1,NULL,0,'disable_shipping_method','','flatrate,tablerate,dhl,fedex,ups,usps,dhlint','2,4,3',1);
INSERT INTO `checkoutrule` (`name`,`description`,`from_date`,`to_date`,`customer_group_ids`,`is_active`,`conditions_serialized`,`actions_serialized`,`stop_rules_processing`,`is_advanced`,`product_ids`,`sort_order`,`simple_action`,`payment_methods_ids`,`shipping_methods_ids`,`website_ids`,`coupon_type`) VALUES ('Bezahlmethode Versand im Werksverkauf','Wenn Kunde im WVK steht aber ohne Abholung bestellen möchte','2014-07-25',NULL,'0,1,2,3,4,5,6,9',1,'a:7:{s:4:\"type\";s:32:\"salesrule/rule_condition_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";s:1:\"1\";s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";s:10:\"conditions\";a:2:{i:0;a:5:{s:4:\"type\";s:32:\"salesrule/rule_condition_address\";s:9:\"attribute\";s:9:\"remote_ip\";s:8:\"operator\";s:2:\"==\";s:5:\"value\";s:11:\"100.0.16.72\";s:18:\"is_value_processed\";b:0;}i:1;a:5:{s:4:\"type\";s:32:\"salesrule/rule_condition_address\";s:9:\"attribute\";s:15:\"shipping_method\";s:8:\"operator\";s:2:\"!=\";s:5:\"value\";s:25:\"freeshipping_freeshipping\";s:18:\"is_value_processed\";b:0;}}}','a:6:{s:4:\"type\";s:40:\"salesrule/rule_condition_product_combine\";s:9:\"attribute\";N;s:8:\"operator\";N;s:5:\"value\";b:1;s:18:\"is_value_processed\";N;s:10:\"aggregator\";s:3:\"all\";}',1,1,NULL,10,'disable_payment_method','free,cashondelivery,paypal_billing_agreement','','2,4,3',1);
");
